### ISSUE TITLE
multiple folders in modules folder according to prefixed IDs

### ISSUE THREAD

**Issue by manaswinidas** [LightGuard/asciidoc-splitter#25]
This remains a question, whether there is a need for multiple folders according to categories inside the modules folder and whether there is a need to add suitable prefixes in the IDs. This is open for discussion.

Related issue: #1

**Comment by LightGuard** [comment]
@sterobin could you comment on this please?

**Comment by sterobin** [comment]
@manaswinidas @LightGuard I assume you're referring to the folders in the modules folder that divide up module files by category. This is an aid to navigation so that it's not a giant pile of adoc files. And we use category folders (`bpmn`, `dmn`, `openshift`, etc) which are more helpful for nav than just dividing by `con`, `proc`, or `ref` folders, which is less helpful. If having subjective category folders is a deal breaker with the splitter, we can reassess. If I've misunderstood the question, let me know.

**Comment by LightGuard** [comment]
It isn't a deal breaker, @sterobin, we would need some way to determine where to put the file is all.

**Comment by sterobin** [comment]
This should be addressed as part of #47 , as illustrated in the example source branch (chap files divided by subject-matter folders).
